# Generated by Django 5.1.3 on 2024-12-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('path', models.CharField(max_length=255, null=True)),
                ('types', models.CharField(max_length=255, null=True)),
                ('component', models.CharField(max_length=255, null=True)),
                ('meta', models.JSONField(null=True)),
                ('redirect', models.CharField(max_length=255, null=True)),
                ('buttons', models.JSONField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.menus')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
    ]
