# Generated by Django 5.1.3 on 2024-12-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menus',
            old_name='parent',
            new_name='parentId',
        ),
        migrations.AddField(
            model_name='menus',
            name='permission',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
